#import "@preview/arkheion:0.1.1": arkheion, arkheion-appendices
#import "@preview/algo:0.3.6": algo, code, comment, d, i
#import "@preview/drafting:0.2.2": inline-note, margin-note
#import "@preview/mannot:0.3.0": markrect

#show figure.caption: set align(left)
#show figure.caption: set text(style: "italic")

// #import "@preview/equate:0.3.2": equate

//// ALTERNATIVE ARTICLE TEMPLATES
// #import "@preview/rubber-article:0.5.0": article, appendix, maketitle
// #import "@preview/starter-journal-article:0.4.0": article, author-meta, appendix
// #import "@preview/elsearticle:0.4.2": *
//
#show: arkheion.with(
  title: [Masked Diffusion Models as Associative Memories],
  authors: (
    (name: "Filippo Elgorni", email: "filippo.elgorni@phd.unibocconi.it", affiliation: [Bocconi University, Milan]),
    (name: "Carlo Lucibello", email: "carlo.lucibello@unibocconi.it", affiliation: [Bocconi University, Milan]),
  ),
  date: datetime.today().display("[day] [month repr:Long] [year]"),
  abstract: [#align(left)[]],
)

// #let note(content) = inline-note(content, fill: gray.lighten(80%), stroke: gray, par-break: false)
#let note(content) = highlight([NOTE: ] + content, fill: gray.lighten(80%))

#let citecolor = rgb("#93430e")
#show cite: set text(fill: citecolor)
#show link: set text(fill: blue)
#show link: underline
#show ref: set text(fill: blue)

// #show: equate.with(breakable: true, sub-numbering: true)
// #set math.equation(numbering: "(1.1)")

#let bx = $bold(x)$
#let bw = $bold(w)$
#let cD = $cal(D)$
#let cL = $cal(L)$
#let int = $integral$
#let prod = $product$
#let pm = $plus.minus$

#outline(depth: 2, indent: n => n * 1em)

= Model
We study a teacher/stuent scenario for autoregressive models. We consider a dataset $cD={bx^mu}_(mu=1)^M$ where sequences $bx^mu in {-1,1}^L$ are generated by the stochastic process:

$
  p(bx | W^star) = prod_(i=1)^L sigma(x_i 1/sqrt(L) sum_(j<i) W^star_(i j) x_j)
$

given $W^star in RR^(L times L )$ fixed. Notice that we can take $W^star$ to be lower triangular without the diagonal, and we choose $W^star_(i j) ~ N(0,gamma^2)$ for $j<i$ and $W^star_(i j)=0$ otherwise. The dataset is generated by sampling $M$ sequences from the above distribution.



We then train a student model with matching architecture parametrised by $W$ to generate sequences from the same distribution. $hat(W)$ is obtained by minimizing the negative log-likelihood of the dataset:

$
  cL(W) = - 1/M sum_(mu=1)^M log p(bx^mu | W) = -1/M sum_(mu=1)^M sum_(i=1)^L log sigma(x_i^mu 1/sqrt(L) sum_(j<i) W_(i j) x_j^mu).
$

Due to factorization of the likelihood, minimisation happens component-wise on
$
  cL_i (W)=-1/M sum_(mu=1)^M log sigma(x_i^mu 1/sqrt(L) sum_(j<i) W_(i j) x_j^mu).
$

= Replica Computation
The minimization problem can be reframed as a statistical mechanics problem. We optimise each row of $w_j=W_(i j)$ inipendently, and we can write the partition function for the $i$-th row as:
$
  Z_i=int dif bw e^(-beta lambda/2 ||bw||^2-M beta cL_i (W))=int dif bw e^(-beta lambda/2 ||bw||^2+beta sum_(mu=1)^M log sigma(x_i^mu 1/sqrt(L) sum_(j<i) w_j x_j^mu))
$

The replicated partition function is then:

$
  EE_(X,W^star) [Z_i^n] &= EE_(X,W^star)p int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2+beta sum_(mu, a) log sigma(x_i^mu 1/sqrt(L) sum_(j<i) w_j^a x_j^mu))\
  &= EE_(W^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2) prod_(mu=1)^M [EE_(bx^mu | W^star)thin e^(beta sum_a log sigma(x_i^mu 1/sqrt(L) sum_(j<i) w_j^a x_j^mu))]\
  &= EE_(W^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2) [EE_(bx | W^star)thin e^(beta sum_a log sigma(x_i 1/sqrt(L) sum_(j<i) w_j^a x_j))]^M\.
$

Let's separate the sources of disorder. Call $W^star_(<i)$ the submatrix of $W^star$ with rows and columns smaller than  $i$, while $W^star_i$ is the $i$-th row of $W^star$.  The "prefix" $x_(<i)$ is generated by $W^star_(<i)$, while $x_i$ is generated by $W^star_i$ given $x_(<i)$. Notice that $W^star_(<i)$ an $W^star_(i)$ are independent.

$
  P(x_i | x_(<i), W_i^star) = sigma(x_i 1/sqrt(L) W_i^star dot x_(<i))
$

Then we can write:

$
  EE_(X,W^star) [Z_i^n] &= EE_(W_i^star, W_(<i)^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2) [EE_(x_(<i) | W^*_(<i))thin sum_(x_i=pm 1) e^(log sigma(x_i h_0) + beta sum_a log sigma(x_i h_a))]^M
$

where

$
  h_0 = 1/sqrt(L) W_i^star dot x_(<i), quad quad h_a = 1/sqrt(L) w^a dot x_(<i)
$

#bibliography("bibliography.bib")

#show: arkheion-appendices

