#import "@preview/arkheion:0.1.1": arkheion, arkheion-appendices
#import "@preview/algo:0.3.6": algo, code, comment, d, i
#import "@preview/drafting:0.2.2": inline-note, margin-note
#import "@preview/mannot:0.3.0": markrect

#show figure.caption: set align(left)
#show figure.caption: set text(style: "italic")

// #import "@preview/equate:0.3.2": equate

//// ALTERNATIVE ARTICLE TEMPLATES
// #import "@preview/rubber-article:0.5.0": article, appendix, maketitle
// #import "@preview/starter-journal-article:0.4.0": article, author-meta, appendix
// #import "@preview/elsearticle:0.4.2": *
//
#show: arkheion.with(
  title: [Autoregressive Teacher-Student],
  authors: (
    (name: "Filippo Elgorni", email: "filippo.elgorni@phd.unibocconi.it", affiliation: [Bocconi University, Milan]),
    (name: "Carlo Lucibello", email: "carlo.lucibello@unibocconi.it", affiliation: [Bocconi University, Milan]),
  ),
  date: datetime.today().display("[day] [month repr:Long] [year]"),
  abstract: [#align(left)[]],
)

// #let note(content) = inline-note(content, fill: gray.lighten(80%), stroke: gray, par-break: false)
#let note(content) = highlight([NOTE: ] + content, fill: gray.lighten(80%))

#let citecolor = rgb("#93430e")
#show cite: set text(fill: citecolor)
#show link: set text(fill: blue)
#show link: underline
#show ref: set text(fill: blue)

// #show: equate.with(breakable: true, sub-numbering: true)
// #set math.equation(numbering: "(1.1)")

#let bx = $bold(x)$
#let bw = $bold(w)$
#let cD = $cal(D)$
#let cL = $cal(L)$
#let int = $integral$
#let prod = $product$
#let pm = $plus.minus$

#outline(depth: 2, indent: n => n * 1em)

= Model
We study a teacher/stuent scenario for autoregressive models. We consider a dataset $cD={bx^mu}_(mu=1)^M$ where sequences $bx^mu in {-1,1}^L$ are generated by the stochastic process:

$
  p(bx | W^star) = prod_(i=1)^L sigma(x_i 1/sqrt(L) sum_(j<i) W^star_(i j) x_j)
$

given $W^star in RR^(L times L )$ fixed. Notice that we can take $W^star$ to be lower triangular without the diagonal, and we choose $W^star_(i j) ~ cal(N)(0,gamma^2)$ for $j<i$ and $W^star_(i j)=0$ otherwise. The dataset is generated by sampling $M$ sequences from the above distribution. Notice that $gamma$ controls the "repetiveness" of the sequences inside the dataset. Indeed, write $W^star = gamma U^star$ with $U^star_(i, j<i) ~ cal(N)(0,1)$. Then we have

$
  p(bx | W^star) -> cases(
    prod_(i=1)^L Theta(x_i 1/sqrt(L) sum_(j<i) U^star_(i j) x_j) & " if " gamma->oo,
    1/2^L & " if " gamma->0,
  )
$

so in the former case the sequences are deterministic given $U^star$ and in the latter they are completely random.

We then train a student model with matching architecture parametrised by $W$ to generate sequences from the same distribution. $hat(W)$ is obtained by minimizing the negative log-likelihood of the dataset:

$
  cL(W) = - 1/M sum_(mu=1)^M log p(bx^mu | W) = -1/M sum_(mu=1)^M sum_(i=1)^L log sigma(x_i^mu 1/sqrt(L) sum_(j<i) W_(i j) x_j^mu).
$

Due to factorization of the likelihood, minimisation happens component-wise on
$
  cL_i (W_i)=-1/M sum_(mu=1)^M log sigma(x_i^mu 1/sqrt(L) sum_(j<i) W_(i j) x_j^mu).
$

= Replica Computation
The minimization problem can be reframed as a statistical mechanics problem. We optimise each row of $w_j=W_(i j)$ inipendently, and we can write the partition function for the $i$-th row as:
$
  Z_i=int dif bw e^(-beta lambda/2 ||bw||^2-M beta cL_i (W))=int dif bw e^(-beta lambda/2 ||bw||^2+beta sum_(mu=1)^M log sigma(x_i^mu 1/sqrt(L) sum_(j<i) w_j x_j^mu))
$

The replicated partition function is then:

$
  EE_(X,W^star) [Z_i^n] &= EE_(X,W^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2+beta sum_(mu, a) log sigma(x_i^mu 1/sqrt(L) sum_(j<i) w_j^a x_j^mu))\
  &= EE_(W^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2) prod_(mu=1)^M [EE_(bx^mu | W^star)thin e^(beta sum_a log sigma(x_i^mu 1/sqrt(L) sum_(j<i) w_j^a x_j^mu))]\
  &= EE_(W^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2) [EE_(bx | W^star)thin e^(beta sum_a log sigma(x_i 1/sqrt(L) sum_(j<i) w_j^a x_j))]^M\.
$

Let's separate the sources of disorder. Call $W^star_(<i)$ the submatrix of $W^star$ with rows and columns smaller than  $i$, while $bw^star_i$ is the $i$-th row of $W^star$.  The "prefix" $bx_(<i)$ is generated by $W^star_(<i)$, while $x_i$ is generated by $bw^star_i$ given $bx_(<i)$.

$
  P(x_i | bx_(<i), bw_i^star) = sigma(x_i 1/sqrt(L) bw_i^star dot bx_(<i))
$

Since $W^star_(<i) perp bw^star_(i)$ are  we can write:

$
  EE_(X,W^star) [Z_i^n] &= EE_(bw_i^star, W_(<i)^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2) [EE_(bx_(<i) | W^*_(<i))thin sum_(x_i=pm 1) e^(log sigma(x_i h_0) + beta sum_a log sigma(x_i h_a))]^M
$

where

$
  h_0 (bw_i^star, bx_(<i)) = 1/sqrt(L) bw_i^star dot bx_(<i), quad quad h_a (w^a,bx_(<i)) = 1/sqrt(L) bw^a dot bx_(<i)
$

Define, given $W^star_(<i)$ and $j,k<i$
$
  C_(j k)^((i))=EE_(bx_(<i) | W^star_(<i)) [x_j x_k].
$
Define
$
  q_(a b) & = EE_(bx_(<i) | W^star_(<i)) [h_a h_b]= 1/L (bw^a)^top C^((i)) bw^b, \
      m_a & = EE_(bx_(<i) | W^star_(<i)) [h_a h_0]= 1/L (bw_i^star)^top C^((i)) bw^a.
$

Notice that in usual teacher-student scenarios, $C=I$ since it is made of independent random variables. Here instead, we will have some correlations between tokens of the prefix. Notice how only depends on the prefix matrix $W_(<i)^star$. Since $EE_(bx_(<i) | W^star_(<i)) [x_i]=0$ due to the symmetry of the model, we have $EE_(bx_(<i) | W^star_(<i)) [h_0]= EE_(bx_(<i) | W^star_(<i)) [h_a]=0$. We assume the following GEP:
$
  (h_0, h_1, ..., h_n) ~ cal(N)(0, Sigma) quad quad Sigma = mat(gamma^2 t, m_1, ..., m_n; m_1, q_(1 1), ..., q_(1 n); ...; m_n, q_(n 1), ..., q_(n n))
$

where the dependence of the order parameters on $i$ (or $t$) is implicit. We used the fact that $(bw_i^star)^top C bw_i^star = gamma^2 L t$ where $t=i \/L$, since $bw_i^star$ is independent of the prefix weights. We can then write

$
  EE_(X,W^star) [Z_i^n] = & EE_(W_(<i)^star, bw_i^star) int prod_(a b) (dif q^(a b) dif hat(q)^(a b))/(2 pi) prod_a (dif m^a dif hat(m)^a)/(2 pi) prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2)times \
  & times [int dif h_0 prod_a dif h_a e^log(sum_(x_i=pm 1) sigma(x_i h_0) prod_a sigma(x_i h_a)^beta)
    cal(N)(h_0, h_1, ..., h_n; 0, Sigma)]^M \
  & times e^(i L sum_(a b) hat(q)^(a b) (q_(a b)-((bw^a)^top C^((i))bw^b)/L)+i L sum_a hat(m)^a (m_a-((bw^star_i)^top C^((i))bw^a)/L))\
  = & int prod_(a b) (dif q^(a b) dif hat(q)^(a b))/(2 pi) prod_a (dif m^a dif hat(m)^a)/(2 pi) e^(i L sum_(a b) hat(q)^(a b) q_(a b)+i L sum_a hat(m)^a m_a) \
  & times [int dif h_0 prod_a dif h_a e^log(sum_(x_i=pm 1) sigma(x_i h_0) prod_a sigma(x_i h_a)^beta)
    cal(N)(h_0, h_1, ..., h_n; 0, Sigma)]^M \
  & times EE_(W_(<i)^star, bw_i^star) int prod_a dif bw^a e^(-beta lambda/2 sum_a ||bw_a||^2-i L sum_(a b) hat(q)^(a b)(sum_(j k) w^a_j C^((i))_(j k)(W^star_i) w^b_i)/L-i L sum_a hat(m)^a (sum_(j k)w^star_i_j C^((i))_(j k)(W^star_i) w^a_i)/L)
$

== Spectrum of $C^((i))$
To continue we need the spectrum of the matrix $C^((i))$, which will expect to concentrate.




#bibliography("bibliography.bib")

#show: arkheion-appendices

